# Collections

## Counter()

In [1]:
from collections import Counter
c = Counter()

In [2]:
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

In [3]:
c = Counter(cars)
print(c)

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [4]:
print(c['black'])

3


### Сумма

In [5]:
print(sum(c.values()))

9


In [6]:
print(c.values())

dict_values([3, 2, 3, 1])


### Сложение, Вычитание

In [19]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

In [20]:
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow)
print(counter_spb)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})


In [21]:
print(counter_moscow + counter_spb)

Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})


In [70]:
print(counter_moscow)
print(counter_spb)
 
counter_moscow.subtract(counter_spb)
print(f'moscow - spb {counter_moscow}')

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
moscow - spb Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [23]:
# Пересоздаём счётчики, потому что объект counter_moscow поменял свои значения
# после функции subtract.
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow - counter_spb)

Counter({'black': 2, 'yellow': 1})


### Распаковка итератора  (*)

In [ ]:
# посмотреть все элементы списка/счётчика/словаря =)
print(*counter_moscow.elements())

black black black black white white yellow yellow yellow


In [25]:
# Список уникальных элементов
print(list(counter_moscow))

['black', 'white', 'yellow']


In [26]:
# превратить в обычный словарь
print(dict(counter_moscow))

{'black': 4, 'white': 2, 'yellow': 3}


In [29]:
# получаем список из кортежей элементов в порядке убывания
print(counter_moscow.most_common())
print(counter_moscow.most_common(2)) # ограничеваем число 
                             #    -отображаемых элементов

[('black', 4), ('yellow', 3), ('white', 2)]
[('black', 4), ('yellow', 3)]


## Defaultdict

In [30]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

In [31]:
groups = dict()
 
for student, group in students:
    # Проверяем, есть ли уже эта группа в словаре
    if group not in groups:
        # Если группы ещё нет в словаре, создаём для неё пустой список
        groups[group] = list()
    groups[group].append(student)
 
print(groups)

{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}


In [32]:
from collections import defaultdict
groups = defaultdict(list)

In [33]:
for student, group in students:
    groups[group].append(student)
 
print(groups)

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [34]:
print(groups[3])

['Petrov', 'Markov']


## OrderedDict 

In [37]:
# Напоминаем способ создания словаря через список кортежей
# (ключ, значение)
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
client_ages = dict(data)
print(client_ages)

{'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20}


Специальный словарь, который гарантирует сохранение ключей в порядке их добавления, называется OrderedDict:

In [38]:
from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)

OrderedDict({'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20})


## Deque "дек" - очередь

In [39]:
from collections import deque
dq = deque()
print(dq)

deque([])


У deque есть четыре ключевые функции:

append (добавить элемент в конец дека);
appendleft (добавить элемент в начало дека);
pop (удалить и вернуть элемент из конца дека);
popleft (удалить и вернуть элемент из начала дека).

In [41]:
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)
print(clients[2])

deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
Smirnov


In [ ]:
# добавляем в начало очереди
clients.appendleft('Vip-client')
print(clients)

deque(['Vip-client', 'Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])


In [ ]:
# удаляем из начала очереди
tired_client = clients.pop()
print(tired_client, "left the queue")
print(clients)

Tikhonova left the queue
deque(['Vip-client', 'Ivanov', 'Petrov', 'Smirnov'])


In [ ]:
clients = deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
print(clients)
# Удаляем клиента номер 3
del clients[2]  
print(clients)

deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
deque(['Ivanov', 'Petrov', 'Tikhonova'])


Также в очередь возможно добавить сразу несколько элементов из итерируемого объекта в дек. Для этого используют функции extend (добавить в конец дека) и extendleft (добавить в начало дека).

In [46]:
# В скобках передаём список при создании deque,
# чтобы сразу добавить все его элементы в очередь
shop = deque([1, 2, 3, 4, 5])
print(shop)

shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])


In [ ]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
# добавить слева(в начало очереди с переворотом)
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 3, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])


In [ ]:
# максимальная длина очереди
limited = deque(maxlen=3)
print(limited)
 
limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)

deque([], maxlen=3)
deque([5, 6, 7], maxlen=3)


In [49]:
limited.extend([1,2,3])
print(limited)
 
print(limited.append(8))
print(limited)

deque([1, 2, 3], maxlen=3)
None
deque([2, 3, 8], maxlen=3)


In [50]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

In [51]:
days = deque(maxlen=7)
 
for temp in temps:
    # Добавляем температуру в очередь
    days.append(temp)
    # Если длина очереди оказалась равной максимальной длине очереди (7),
    # печатаем среднюю температуру за последние 7 дней
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
# Напечатаем пустую строку, чтобы завершить действие параметра
# end. Иначе следующая строка окажется напечатанной на предыдущей
print("")

20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97; 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4; 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67; 


In [53]:
# reverse позволяет поменять порядок элементов в очереди на обратный:
dq = deque([1,2,3,4,5])
print(dq)
 
dq.reverse()
print(dq)

deque([1, 2, 3, 4, 5])
deque([5, 4, 3, 2, 1])


In [ ]:
# rotate переносит n заданных элементов из конца очереди в начало:

dq = deque([1,2,3,4,5])
print(dq)
 
dq.rotate(2)
print(dq)

deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])


In [55]:
dq = deque([1,2,3,4,5])
print(dq)
 
# Отрицательное значение аргумента переносит
# n элементов из начала в конец
dq.rotate(-2)
print(dq)

deque([1, 2, 3, 4, 5])
deque([3, 4, 5, 1, 2])


In [64]:
#  index позволяет найти первый индекс искомого элемента,
# а count позволяет подсчитать, сколько раз элемент встретился в очереди
dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
print(dq.index(4))
print(dq.count(4))# вхождения 

2
6


In [ ]:
# clear позволяет очистить очередь:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq)
dq.clear()
print(dq)

# Задача

In [69]:
temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5), ('2004', -8.2), ('2005', -1.6), ('2006', -5.9), ('2007', -2.4), ('2008', -1.7), ('2009', -3.5), ('2010', -12.1), ('2011', -5.8), ('2012', -4.9), ('2013', -6.1), ('2014', -6.9), ('2015', -2.7), ('2016', -11.2), ('2017', -3.9), ('2018', -2.9), ('2019', -6.5), ('2020', 1.5)]

def check(temps):
    sort_temp = OrderedDict(sorted(temps, key=lambda x: -x[1]))
    return sort_temp
print(check(temps))

OrderedDict({'2020': 1.5, '2005': -1.6, '2008': -1.7, '2007': -2.4, '2001': -2.5, '2015': -2.7, '2018': -2.9, '2009': -3.5, '2017': -3.9, '2000': -4.4, '2002': -4.4, '2012': -4.9, '2011': -5.8, '2006': -5.9, '2013': -6.1, '2019': -6.5, '2014': -6.9, '2004': -8.2, '2003': -9.5, '2016': -11.2, '2010': -12.1})


# NumPy библиотеки

### Целочисленные типы данных в NumPy

In [1]:
import numpy as np

In [75]:
# np.iinfo(np.int8)
# np.iinfo(np.int16)
# np.iinfo(np.int32)
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [76]:
b = np.uint8(124)
print(b)

print(type(b))

np.iinfo(b)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [77]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.longdouble'>
<class 'numpy.longlong'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.ulonglong'>
<class 'numpy.void'>


## Масствы

In [2]:
arr = np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [7]:
arr[2] = 2000
arr

/tmp/ipykernel_4273/4005198755.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr[2] = 2000


array([  1,   5, -48,   9,  10], dtype=int8)

In [8]:
arr = np.float128(arr)
arr

array([  1.,   5., -48.,   9.,  10.], dtype=float128)

In [9]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [11]:
# Узнать размерность массива можно с помощью .ndim:
arr.ndim

1

In [12]:
nd_arr.ndim

2

In [ ]:
# Узнать общее число элементов в массиве можно с помощью .size:
arr.size

5

In [14]:
# Форма или структура массива хранится в атрибуте .shape:
arr.shape

(5,)

In [15]:
nd_arr.shape

(3, 3)

In [16]:
# Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:

arr.itemsize

1

In [17]:
nd_arr.itemsize

2

In [18]:
# Создадим трёхмерный массив с формой 5x4x3 и типом float32:

zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

In [ ]:
# Создадим массив от 2.5 до 5 с шагом 0.5 и с типом float16:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

Ещё какя-то функция, типо лучше чем  arange :
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;

num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);

endpoint — включён или исключён конец диапазона (по умолчанию включён);

retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;

dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

In [20]:
# Давайте потренируемся. Создадим массив из десяти чисел между 1 и 2:

arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [21]:
# Создадим массив из десяти чисел между 1 и 2, не включая 2:

arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [22]:
# Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

0.1111111111111111


In [23]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1


In [37]:
marr = np.linspace(-6, 21, 60)
marr, marr_step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(marr_step, 2))

0.45


In [36]:
# DeepSeek
arr = np.linspace(-6, 21, 60)
step = round(arr[1] - arr[0], 2)  # 0.46
print(step)

0.46


### Изменение формы массива

In [38]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
# Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы. Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:

In [41]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [42]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# Транспонируем его:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [44]:
# При транспонировании одномерного массива его форма не меняется:

arr = np.arange(3)
print(arr.shape)

(3,)


In [45]:
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)


### Индексы и срезы в массивах

In [46]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [47]:
# Обратиться к его элементу по индексу можно так же, как и к списку:

print(arr[2])

1.4


In [48]:
# Привычная запись для срезов работает и для одномерных массивов:

print(arr[2:4])

[1.4 1.6]


In [49]:
# Наконец, напечатать массив в обратном порядке можно с помощью привычной конструкции [::-1]:

print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [50]:
# С многомерными массивами работать немного интереснее. Создадим двумерный массив из одномерного:

nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [51]:
nd_array[1][2]

3.0

In [52]:
nd_array[1, 2]

3.0

In [54]:
# Также через запятую можно передавать срезы или даже их комбинации с индексами. Например, получим все элементы из колонки 3 для первых двух строк:

nd_array[:2, 2]

array([1., 3.])

In [53]:
# Можно применять срезы сразу и к строкам, и к столбцам:

nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [56]:
# Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие. Например, из всех строк получим срез с третьего по четвёртый столбцы:

nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [57]:
# Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно. Строки будут получены целиком по умолчанию:

nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

### Сортировка одномерных массивов

In [58]:
# Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:

arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)

print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [59]:
# Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:

arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())

print(arr)

None
[ 3  4 12 12 15 23 23 45]


Работа с пропущенными данными

In [60]:
data = np.array([4, 9, -4, 3])
# Воспользуемся встроенной в NumPy функцией sqrt, чтобы посчитать квадратные корни из элементов.

roots = np.sqrt(data)
roots

/tmp/ipykernel_4273/2484779739.py:4: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [61]:
# Можно заполнить пропущенные значения, например, нулями. Для этого с помощью функции np.isnan(<массив>) узнаем, на каких местах в массиве находятся «не числа»:

np.isnan(roots)

array([False, False,  True, False])

In [ ]:
# Можно использовать полученный массив из True и False для извлечения элементов из массива roots, на месте которых в булевом массиве указано True. 
# Таким способом можно узнать сами элементы, которые удовлетворяют условию np.isnan:

roots[np.isnan(roots)]

array([nan])

In [63]:
# Этим элементам можно присвоить новые значения, например 0:

roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [64]:
# После этого, если пропущенных значений больше нет, можем подсчитать сумму элементов массива:

sum(roots)

6.732050807568877

In [65]:
np.isnan(np.nan)

True

### Векторы в NumPy и арифметика
С векторами в NumPy можно производить арифметические операции: складывать, вычитать, умножать друг на друга, возводить один вектор в степень другого и т. д.

In [66]:
# Произведём сложение двух векторов:

import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [67]:
# Что бы произошло при сложении двух списков? Их элементы просто объединились бы в один список:

list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [68]:
# Поэлементно умножим два вектора одинаковой длины:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [69]:
vec = np.arange(5)
vec * 10

vec ** 2

array([ 0,  1,  4,  9, 16])

In [73]:
# Также векторы можно сравнивать друг с другом поэлементно:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6 , 3.6, 13])
 
vec1 > vec2

array([False, False,  True, False])

In [71]:
# Аналогично можно сравнивать вектор с числом:

vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

Продвинутые операции с векторами

In [74]:
vec = np.array([3, 4])

Но можно было поступить проще. В NumPy есть специальный подмодуль linalg, который позволяет производить операции из линейной алгебры.

In [75]:
# Для вычисления длины вектора нам потребуется функция norm:

length = np.linalg.norm(vec)
print(length)

5.0


расстояние между векторами — это длина такого вектора, который является разностью этих векторов.

In [76]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [ ]:
# скалярным произведением двух векторов называют сумму произведений их соответствующих координат
# Для этого используют функцию np.dot(x, y):
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [79]:
# равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:

x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

In [81]:
a = [23, 34, 27]
b = [-54,   1,  46] 
c = [46, 68, 54]

сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов.

In [ ]:
d = np.linalg.norm(a)
e = np.linalg.norm(b)
f = np.linalg.norm(c)


In [82]:
# Заданные векторы
a = np.array([23, 34, 27])
b = np.array([-54, 1, 46])
c = np.array([46, 68, 54])

# Функция для проверки сонаправленности
def are_codirectional(u, v):
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    return np.isclose(dot_product, norm_u * norm_v)

# Проверяем все пары векторов
pairs = [("a и b", a, b),
         ("b и c", b, c),
         ("a и c", a, c)]

for name, u, v in pairs:
    if are_codirectional(u, v):
        print(f"Пара {name} сонаправлена")
        break
else:
    print("Такой пары нет")

# Дополнительная проверка суммы длин и длины суммы для сонаправленных векторов
for name, u, v in pairs:
    if are_codirectional(u, v):
        sum_lengths = np.linalg.norm(u) + np.linalg.norm(v)
        length_of_sum = np.linalg.norm(u + v)
        print(f"Для пары {name}:")
        print(f"Сумма длин: {sum_lengths:.2f}")
        print(f"Длина суммы: {length_of_sum:.2f}")
        print(f"Равны: {np.isclose(sum_lengths, length_of_sum)}")
        break

Пара a и c сонаправлена
Для пары a и c:
Сумма длин: 147.40
Длина суммы: 147.40
Равны: True


In [84]:
# Заданные векторы
a = np.array([23, 34, 27])
b = np.array([-54, 1, 46])
c = np.array([46, 68, 54])

# Проверяем все возможные пары
pairs = [("a и b", a, b),
         ("a и c", a, c),
         ("b и c", b, c)]

# Функция для проверки перпендикулярности
def are_perpendicular(u, v):
    return np.isclose(np.dot(u, v), 0)

# Ищем перпендикулярные пары
for name, u, v in pairs:
    if are_perpendicular(u, v):
        print(f"Пара {name} перпендикулярна (скалярное произведение = {np.dot(u, v):.1f})")
        break
else:
    print("Перпендикулярных пар нет")

Перпендикулярных пар нет


### Базовые статистические функции для векторов

In [85]:
# Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. 
# Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():

vec = np.array([2,7,18,28,18,1,8,4])
vec.min()

1

In [86]:
np.max(vec)

28

In [87]:
# Функция mean позволяет посчитать среднее значение. Больше не требуется реализовывать её «руками»!

vec.mean()

10.75

In [88]:
# Вычисление медианы
median_value = np.median(vec)

print("Медиана:", median_value)

Медиана: 7.5


In [89]:
# стандартное отклонение значений в массиве
std_dev = round(np.std(vec),2)
print(std_dev)

8.95


### Случайные числа в NumPy
Генерация float

In [90]:
# Для генерации псевдослучайных чисел в NumPy существует подмодуль random.

# Самой «базовой» функцией в нём можно считать функцию rand. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

import numpy as np
np.random.rand()

0.009079737178654623

In [91]:
# Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:

np.random.rand() * 100

23.7024423172035

In [92]:
# На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов через запятую целые числа,
# которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:

np.random.rand(5)

array([0.90989529, 0.89627152, 0.77838203, 0.29466662, 0.37687829])

In [93]:
# Массив из двух случайных строк и трёх столбцов:

np.random.rand(2, 3)

array([[0.67601312, 0.75015732, 0.52212277],
       [0.49661403, 0.94051056, 0.33349214]])

In [95]:
# Функция rand может принимать неограниченное число целых чисел для задания формы массива:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[7.00185910e-01, 9.81059566e-01, 8.97209622e-01, ...,
            4.60899734e-01, 6.88883206e-01, 6.22771909e-01],
           [9.83802973e-01, 7.38881618e-01, 3.46014534e-01, ...,
            7.94591445e-01, 6.52224151e-01, 4.78454083e-01],
           [9.53638634e-01, 7.39522357e-01, 4.97257674e-01, ...,
            2.02605889e-01, 3.29122416e-01, 9.55048376e-01],
           ...,
           [8.54703443e-01, 8.87555006e-01, 7.84145607e-01, ...,
            7.39971504e-01, 4.40792775e-01, 4.00601479e-01],
           [4.78579682e-01, 6.21722848e-01, 3.98721833e-01, ...,
            3.23594006e-01, 7.29974766e-01, 3.44987181e-01],
           [7.95599390e-01, 8.41131097e-01, 1.56963187e-01, ...,
            7.49964940e-01, 4.27878534e-01, 3.19706101e-01]],

          [[7.88167814e-01, 4.31662692e-01, 4.86746810e-01, ...,
            2.61883205e-01, 8.36304203e-01, 6.52910140e-01],
           [5.13917338e-01, 2.26203771e-01, 5.29364093e-01, ...,
            4.40022748e-01, 7.26303

In [96]:
# Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:

shape = (3, 4)
np.random.rand(*shape)

array([[0.51373185, 0.0424948 , 0.23890421, 0.80198985],
       [0.80864587, 0.552819  , 0.23417327, 0.37838043],
       [0.22055154, 0.88405654, 0.48844739, 0.48540771]])

In [97]:
# Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1,
# которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:

shape = (2, 3)
np.random.sample(shape)

array([[0.92915756, 0.6813606 , 0.92487827],
       [0.24837916, 0.14226948, 0.31719493]])